### ISSUE TITLE
figure out how many vars can go on the same graph and split if too many?

### ISSUE THREAD

**Issue by wzb-ipi** [wzb-ipi/dashdash#7]

**Comment by juliosolisar** [comment]
So we are all seeing graphs like this right? 
![Captura de pantalla 2020-05-05 a las 16 35 53](https://user-images.githubusercontent.com/52597364/81078467-90262100-8eee-11ea-9a34-7f9d67d449f9.png)

**Comment by juliancg24** [comment]
see issue #36
