### ISSUE TITLE
generate report on quality of inputs

### ISSUE THREAD

**Issue by wzb-ipi** [wzb-ipi/dashdash#9]
working with the SL data I run into issues with the measures file, and have to do some fixes:

e.g. 
```
my_vars <- openxlsx::read.xlsx("measures.xlsx") %>%
  filter(!is.na(variable)) %>%
  filter(!duplicated(variable))
```

it would be useful to have a file that checks all inputs and reports duplicates, data missing and so on

**Comment by wzb-ipi** [comment]
checking also that the map data can link to the data$id var

**Comment by juliosolisar** [comment]
> checking also that the map data can link to the data$id var

didn't catch this @macartan

**Comment by macartan** [comment]
I meant that one check should be: are teh various map arguments provided
compatible with the shapefiles -- eg can one implement the broom step in
the code without a hitch?

**Comment by juliosolisar** [comment]
pushed a version of this, but maybe we have to revise soon enough
